---
variables:
  file: &file Dockerfile
  arch: &arch linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8
  dhub: &dhub https://index.docker.io/v1/
  repo: &repo bksolutions/modbus-simulator

steps:
  build_n_push:
    when:
      - event: [push]
        branch: main
        path:
          include: ['Dockerfile', 'requirements.txt', '.py', '.woodpecker/dockerhub_deploy.yml']
      - event: [cron, manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - 'latest'
        - '0.0.1'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS